FinalProjectApplication/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProjectApplication.Models;
using FinalProjectApplication.Manager;
using System.IO;

namespace FinalProjectApplication.Controllers
{
    public class ImageController : Controller
    {
        ImageManager imageManager = new ImageManager();
        //Image oImage = new Image();
        //List<Image> o_Images = new List<Image>();
        // GET: Image
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UploadImage()
        {
            if (Session["UserId"] == null || Convert.ToInt32(Session["Rule"]) != 1)
            {
                return new HttpNotFoundResult("opps,This page is not for you");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadImage(Image image, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                string fileName = Path.GetFileName(file.FileName);
                string imagePath = Path.Combine(Server.MapPath("~/Image/"), fileName);
                file.SaveAs(imagePath);
            }
            image.ImagePath = "~/Image/" + file.FileName;
            ViewBag.Message = imageManager.SaveImage(image);
            return View();
        }

        public ActionResult ShowImage()
        {
            if (Session["UserId"] == null)
            {
                return new HttpNotFoundResult("opps,This page is not for you");
            }
            ViewBag.Message = Session["Message"];
            Session["Message"] = null;
            return View(imageManager.ShowImage());
        }

        public ActionResult DeleteImage(int? id)
        {
            if (Session["UserId"] == null || Convert.ToInt32(Session["Rule"]) != 1)
            {
                return new HttpNotFoundResult("opps,This page is not for you");
            }
            Image image = imageManager.DetailImage(Convert.ToInt32(id));
            ViewBag.Image = image.ImagePath;
            // Session["Message"] = imageManager.DeleteImage(Convert.ToInt32(id));
            return View(image);
        }
        [HttpPost]
        public ActionResult DeleteImage(Image image)
        {
            if (Session["UserId"] == null || Convert.ToInt32(Session["Rule"]) != 1)
            {
                return new HttpNotFoundResult("opps,This page is not for you");
            }
          //  Image image = imageManager.DetailImage(Convert.ToInt32(id));
             Session["Message"] = imageManager.DeleteImage(image.Id);
            return RedirectToAction("ShowImage");
        }
    }
}

FinalProjectApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript">
        function getTimeFromserver() {
            $.ajax({
                url: '/Notification/ShowCount',
                type: 'GET',
                success: function (html) {
                    $('#idOra').html(html);
                }
            });
        }
        $(document).ready(function () {
            setInterval('getTimeFromserver();', 1000);
        });
    </script>
    <style>

        li:hover {
            cursor: pointer;
            background: #2E4A62;
            border-radius: 12px;
            font-weight: bold;
        }

        navbar li.active {
            border-bottom: 3px solid red;
        }

        .mynavbar {
            overflow: hidden;
            background-color: none;
            font-family: Arial, Helvetica, sans-serif;
        }

            .mynavbar a {
                float: left;
                font-size: 16px;
                color: black;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

        .mydropdown {
            float: left;
            overflow: hidden;
        }

            .mydropdown .mydropbtn {
                font-size: 16px;
                border: none;
                outline: none;
                color: darkgray;
                padding: 14px 16px;
                background-color: inherit;
                font-family: inherit;
                margin: 0;
            }

            .mynavbar a:hover, .mydropdown:hover .mydropbtn {
                color: white;
                background-color: #2E4A62;
            }


        .mydropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 170px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .mydropdown-content a {
                float: none;
                color: white;
                background-color: #343148;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .mydropdown-content a:hover {
                    background-color: #2E4A62;
                }

        .mydropdown:hover .mydropdown-content {
            display: block;
        }

        .notiBell:hover {
            cursor: pointer;
            background-color: #2E4A62;
            border-radius: 2px;
            color: white;
        }
    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top " style="padding:10px;border:none;background-color:#343148; color:red;font-size:large;font-family:'Bell MT';">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div style="background:#2E4A62;border-radius:10px;" class="navbar-header">

                    <div class="navbar-header pull-left " style="border-radius:10px;float:left;">
                        &nbsp;
                        <img src="~/Content/logo.JPG" style="width: 45px;">

                    </div>
                    @Html.ActionLink("উৎসর্গ ফাউন্ডেশন", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "font:bold;color:#fff; font-size:18px;" })
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav cursor">
                    @*<li>
                            <a href="@Url.Action("Index", "Home")">
                                <span class="glyphicon glyphicon-home"></span>
                                Home
                            </a>
                        </li>*@
                    @if (Session["UserId"] != null)
                    {

                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>

                        if (Convert.ToInt32(Session["Rule"]) == 1)
                        {


                            <li>
                                <div class="mynavbar">
                                    <div class="mydropdown">
                                        <button class="mydropbtn">
                                            Member
                                            <i class="fa fa-caret-down"></i>
                                        </button>
                                        <div class="mydropdown-content">
                                            <a href="~/Home/MemberList">Member List</a>
                                            <a href="~/Home/Registration">Add Member</a>


                                        </div>
                                    </div>
                                </div>
                            </li>
                        }
                        <li>
                            <div class="mynavbar">
                                <div class="mydropdown">
                                    <button class="mydropbtn">
                                        Event
                                        <i class="fa fa-caret-down"></i>
                                    </button>
                                    <div class="mydropdown-content">
                                        @if (Convert.ToInt64(Session["Rule"]) == 1)
                                        {
                                            <a href="~/Event/CreateEvent">Create</a>
                                        }

                                        <a href="~/Event/ShowRecentEvent">Recent</a>
                                        <a href="~/Event/ShowEvent">Show all Event</a>

                                    </div>
                                </div>
                            </div>
                        </li>


                        <li>

                            <div class="mynavbar">


                                <div class="mydropdown">
                                    <button class="mydropbtn" style="margin-top:-5px;">
                                        <img style="height:35px;width:35px;" src="https://img.pngio.com/blood-droppng-blood-drop-png-500_500.png" alt="Image - Blood Drop.png | Emporea Wiki | FANDOM powered by Wikia">

                                        <i class="fa fa-caret-down"></i>
                                    </button>
                                    <div class="mydropdown-content">
                                        <a href="~/Blood/BloodSearch">Blood Search</a>
                                        <a href="~/Blood/BloodRequest">Blood Request</a>
                                        <a href="~/Blood/ShowAllBloodRequest">Show All Request</a>

                                    </div>
                                </div>
                            </div>

                        </li>
                        if (Convert.ToInt64(Session["Rule"]) != 1)
                        {
                            <li>@Html.ActionLink("Gallery", "ShowImage", "Image")</li>
                        }
                        if (Convert.ToInt64(Session["Rule"]) == 1)
                        {
                            <li>
                                <div class="mynavbar">
                                    <div class="mydropdown">
                                        <button class="mydropbtn">
                                            Image
                                            <i class="fa fa-caret-down"></i>
                                        </button>
                                        <div class="mydropdown-content">

                                            <a href="~/Image/UploadImage">Upload Image</a>
                                            <a href="~/Image/ShowImage">Image Gallery</a>

                                        </div>
                                    </div>
                                </div>
                            </li>
                        }
                        if (Convert.ToInt64(Session["Rule"]) != 4)
                        {
                            <li class="notiBell"><a href="/Notification/Notification" class="notiBell"><h2 class="glyphicon glyphicon-bell" style="color:blue;margin-top:-10px;"></h2><strong id="idOra" style="color:red;"></strong></a></li>
                        }
                    }
                </ul>


                <ul class="nav navbar-nav navbar-right" style="background-color:#2E4A62;border-radius:360px;color:red;">
                    @if (Session["UserId"] != null && Convert.ToInt32(Session["Rule"]) != 4)
                    {
                        <li>
                            <div class="mynavbar">
                                <div class="mydropdown">
                                    <button class="mydropbtn" style="color:white;">
                                        <span class="glyphicon glyphicon-user"></span> @Session["Name"]
                                        <i class="fa fa-caret-down"></i>
                                    </button>
                                    <div class="mydropdown-content">
                                        <a href="~/Home/UpdateProfile">Update Profile</a>
                                        <a href="/Home/Logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a>

                                    </div>
                                </div>
                            </div>
                        </li>

                    }

                    else
                    {
                        if (Convert.ToInt64(Session["Rule"]) == 4)
                        {
                            <li><a href="/Home/Registration" style="color:white;"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                            <li style="color:white;margin-top:12px;">|</li>
                            <li><a href="/Home/Logout" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
                        }
                        else
                        {


                            <li><a href="/Home/Registration" style="color:white;"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                            <li style="color:white;margin-top:12px;">|</li>
                            <li><a href="/Home/Login" style="color:white;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <footer class="navbar-fixed-bottom" style="background-color:#343148;opacity:.7;color:white">
            <p>
                &copy; @DateTime.Now.Year - Utsorgo Foundation
                <a href="https://www.facebook.com/groups/788812434596502"><i class="fa fa-facebook-official"></i></a>
                @*<a href="#"><i class="fa fa-pinterest-p"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-flickr"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>*@
            </p>


        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>